### ISSUE TITLE
Profile pages

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-dataroom#1]
The profile page of the Dataroom application has the following tabs: 

- Profile: The user can set first name, last name and photo. Email address is immutable. Here the user can also remove the username from the database. 
- Password: The user can give the current password and then set a new password. The new password must contain at least 8 characters and must have at least one uppercase letter, one number and one symbol.
- Team: This is only visible to the admin - the first logged-in user. The admin can invite a new user or an admin, change the role or remove other users/admins. The organization name can also be changed here. Initially, the organization name can be a random string, like "Stark Industries", and then can be modified by the admin.

Here is an example screen: 

<img width="1059" alt="Screenshot 2024-08-23 at 12 01 42 AM" src="https://github.com/user-attachments/assets/c55afe8f-789b-4fb7-bb22-2cd4438a9062">

![image](https://github.com/user-attachments/assets/99b9f462-060f-45b1-91fd-1dc2b2837c02)

Tasks: 

- [x] Implement profile tab
   - [x] General layout
   - [x] 3 Text field for names
   - [x] Note that 1 there is one immutable text field for password
   - [x] Update link by clicking on the picture functionality
   - [x] "Delete" button
   - [x] "Update" button
   - [x] "Save" button
   - [x] "Delete account" button

- [x] Implement password tab
   - [x] General layout
   - [x] 3 Text field for password and confirmation
   - [x] Text information what is required at the alert box text location (that is currently showing on Figma)
   - [x] Alert text box when requirements are not met
   - [x] "Save" button

**Note: The uptime-manager repository (https://github.com/bluewave-labs/bluewave-uptime) has all the required code, and it can be reused for this purpose. There might be slight differences between the Figma design and the code we'll use from the Uptime Manager application will supersede the Figma design.**

**Comment by Paxxack** [comment]
Team section have been removed from the profile section and added to it own section accessible from the dropdown menu when user click on his profile tag.
