### ISSUE TITLE
Documents page - Create Link section - 2/2

### ISSUE THREAD

**Issue by Paxxack** [bluewave-labs/bluewave-dataroom#10]
At the end of the "Implement Documents page section 1/2", the last task is to create a popup with a "Create a new link?" and "Add new link" in the action menu functionality. This popup will redirect the user back to this section. Both sections can be worked on separately and then integrated together afterward.

![image](https://github.com/user-attachments/assets/fcd16517-9417-48e9-b25d-86a726657978)
![image](https://github.com/user-attachments/assets/6ea846fb-15e0-4632-a626-5e5d59a5093b)

- [x] Accordion Menu popup

- [x] "Link details" section
   - [x] 2 Field required 
   - [x] Copy past button ( on the right side of the first field )
   - [x] "Status" checkbox functionality (???)

- [x] Sharing options section
   - [x] "Ask for the following..." checkbox
   - [x] Information required for viewing dropdown selector menu
   - [x] "Require a pass..." checkbox
   - [x] Text field with "placeholder property" (missing on Figma) 
   - [x] Hide or Show button beside the password text field
   - [x] "Expiration" checkbox
   - [x] Double option radio
      - [x] Number of days or...
      - [x] Available until date
         - [x] Calendar popup

- [x] "Sending" section
   - [x] "Select from the..." checkbox
   - [x] Contact dropdown list selector
   - [x] "Send someone not..." checkbox
   - [x] Input text field to caption valid email adresse

- [x] Submit "Generate" button become active only when all field have been filled up

**Comment by gorkem-bwl** [comment]
The implementation of this is also added to #6 @Paxxack , fyi.
