### ISSUE TITLE
Elaborating task listing and finalizing feature design

### ISSUE THREAD

**Issue by Paxxack** [bluewave-labs/bluewave-dataroom#11]
Here is a list of task I need to finalize during the rest of this week and and maybe few days next week.

- [x] Task listing
   - [x] Settings section
   - [x] Contact section
   - [x] File details section
   - [x] Profile / Team section
   - [x] Review and finalize Document section 

- [x] Feature design ( done in collaboration with Gorkem )
    - [x] Documents section
    - [x] Profile / Team section
    - [x] Contact Section
    - [x] File details section

**Comment by Paxxack** [comment]
This task is completed for the MVP version. It was concluded with our meeting with Neeraj and Gorkem on Monday September 2nd 2024.

**Comment by gorkem-bwl** [comment]
Great! Here we go!
