### ISSUE TITLE
Develop Backend for Password Tab

### ISSUE THREAD

**Issue by mahid797** [bluewave-labs/bluewave-dataroom#115]
#### **Description**
Create the backend functionality for the Password tab to enable users to update their password.

#### **Tasks**
- [x] **Password Update API**:
  - Implement/Modify an API that accepts the current password, new password, and confirmation password.
  - Validate the current password for the authenticated user.
  - Enforce strong password requirements and ensure new and confirmation passwords match.
  - Update the password in the database.
- [x] **Integration Decision**:
  - Determine whether to modify the `resetPass` API to include the current password or create a separate API for changing passwords inside the app.
- [x] **Error Handling**:
  - Handle errors such as:
    - Incorrect current password.
    - New password failing validation rules.
    - Server errors.

#### **Tests to Ensure Functionality**
- Validate API behavior for valid and invalid password update scenarios.
- Test authentication and authorization for the password update functionality.
- Ensure proper error messages are returned for invalid inputs.

**Comment by SajanGhuman** [comment]
All tasks done! Issue closed.

**Comment by gorkem-bwl** [comment]
Is it possible to show an end-to-end demo for this one on Monday?
