### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by Paxxack** [bluewave-labs/bluewave-dataroom#12]
Team section is where the user's can manage group of people working on the same project. 

![image](https://github.com/user-attachments/assets/13c7de2d-82a3-43b1-9bea-08855a402ddc)

- [x] Team section
   - [x] General layout
   - [x] Organization name edit button ( pen icon )
   - [x] Tab functionality for displaying administrator only or members
   - [x] "Invite team member" button
   - [x] List of member
   - [x] In role section a dropdown menu for setting the member's role
   - [x] Delete button for each member

**Comment by syedabduldrehman** [comment]
@Paxxack I would suggest for each requirement assigned we add Figma design screenshots, which would be more 
and clear. Any thoughts on this?

**Comment by gorkem-bwl** [comment]
@syedabduldrehman sure - we can do. In fact we do this for every task that is related to a design, but the Team page has recently been added on its own, and I believe @Paxxack will add this soon.

**Comment by Paxxack** [comment]
Sorry for the delay I had a bit of stuff on my plate. Every task has been updated with images.
