### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by Paxxack** [bluewave-labs/bluewave-dataroom#13]
In this section the user can change the settings of different options for his organization.

![image](https://github.com/user-attachments/assets/a90acc99-c779-4234-b87a-bdc26eeb1792)

- [x] Settings page
   - [x] General layout
   - [x] Logo when clicked it open the same functionality than "Update" button
   - [x] "Delete" button
   - [x] "Update" button
   - [x] Color picker functionality either from the "Square color picker with slider" or entering a hex code
   - [x] Same than above for the "Font color"
   - [x] "Save" button

** Notes: The "Back" button have been removed because it is going nowhere at the moment but clarification is needed for this to be official **

**Comment by gorkem-bwl** [comment]
Let's add the corresponding Figma designs to this as well.
