### ISSUE TITLE
First login & Sign in & Forgot password pages

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-dataroom#2]
Since the BlueWave DataRoom application is a self hosted, open source service without any dependencies on paid 3rd party apps and cloud services, the admin should be able to create an account on it once it is deployed. 

The account creation page must be immediately available, and then invisible to the outside, since it will be used only once for the "first" admin user. This admin user will then be able to create other users as well. 

If a user is invited by the admin, then the email link that is sent to the user will include a page that has the email pre-filled, and the user will only be entering name, surname and password to create an account on the system.

**Note: The uptime-manager repository (https://github.com/bluewave-labs/bluewave-uptime) has all the required code, and it can be reused for this purpose. There might be slight differences between the Figma design and the code we'll use from the Uptime Manager application will supersede the Figma design.**

Tasks (all include the UI design and connecting to the backend):

- [ ] Implementation of the "Admin account creation" page
   - [ ] Overall visual layout
   - [ ] Form with 5 required field
   - [ ] Make sure valid email must be entered
   - [ ] Make sure minimum criteria have been entered by user
   - [ ] Toggle password visibility function
- [x] Implementation of the "Login" page
   - [x] Form with 2 required field and submit button
   - [x] "Remember for 30 days" checkbox functionality
   - [x] "Forgot password" link functionality
   - [x]  Submit button functionality
   - [x] "Sign up" link functionality
- [ ] Implementation of "Create an account" page
   - [ ] Form with 5 required field 
   - [ ] Make sure valid email must be entered
   - [ ] Make sure minimum criteria have been entered by user
   - [ ] Submit button functionality
   - [ ] Toggle password visibility function
- [ ] Implementation of the "Forgot password" page
   - [ ] Form with 1 text field for email
   - [ ] Make sure valid email must be entered
   - [ ] Submit button functionality
   - [ ] "Back to sing in" link/button functionality
- [ ] Implementation of "Check your email" page
   - [ ] "Click to resend" functionality
   - [ ] "Back to sign in" link/button
- [ ] Implementation of "Set new password" page
   - [ ] Form with 2 required field 
   - [ ] Make sure that the password entered is not visible and only "*" characters  are visible instead
   - [ ] Make sure minimum criteria have been entered by user
   - [ ] Submit button functionality
   - [ ] "Back to sign in" link/button
- [ ] Implementation of "Password reset"  confirmation page
   - [ ] "Continue" button
   - [ ] "Back to sign in" link/button

**Comment by Paxxack** [comment]
List readjusted and up to date. Removed some comment lines and added few bullet points needed after design adjustments.
