### ISSUE TITLE
Update document

### ISSUE THREAD

**Issue by Paxxack** [bluewave-labs/bluewave-dataroom#28]
In the document section of the app the user can click on the main drag and drop component at the top of the screen to make this popup show up. Or he can click on the action menu and select update document. Here is what it look like:

![image](https://github.com/user-attachments/assets/b490ac9d-780c-4454-82c9-3add0fcb7a88)

Task is to create a component which could be reusable anywhere in the app if needed.

- [ ] General layout
- [ ] Click to upload "button" text
- [ ] Drag and drop functionality
- [ ] Update button
- [ ] Whole thing in a reusable component

**Comment by gorkem-bwl** [comment]
Please find the gap / spacing information here @SepidehShahbazi 

<img width="811" alt="Screenshot 2024-09-23 at 1 26 55 PM" src="https://github.com/user-attachments/assets/12267c74-75f7-4a9a-b314-647654578170">

[Link to Figma design](https://www.figma.com/design/GLFfhwOQeHmbcflgCTuMKA/DataRoom-(Secure-File-Server)?node-id=966-5737&t=7wxu59ALZo5utWcG-1)
