### ISSUE TITLE
Delete file

### ISSUE THREAD

**Issue by Paxxack** [bluewave-labs/bluewave-dataroom#29]
In the document section of the app the user can click on the action menu and choose to "Delete" a file. A confirmation box will appear. Here what it look like:

![image](https://github.com/user-attachments/assets/751a4844-8113-4160-a5c9-73e239dcecca)

Task is to create a component which would probably used for the delete account functionality.

- [ ] General layout
- [ ] "Cancel" button
- [ ] "Delete file" button
- [ ] Whole thing in a reusable component

**Comment by gorkem-bwl** [comment]
@SepidehShahbazi Please find the spacing information for this popup below.

<img width="847" alt="Screenshot 2024-09-25 at 12 05 19 AM" src="https://github.com/user-attachments/assets/b0b8df71-9e66-445b-9e7d-f79b87359606">

[Here is the link to the Figma design](https://www.figma.com/design/GLFfhwOQeHmbcflgCTuMKA/DataRoom-(Secure-File-Server)?node-id=952-4367&t=xmvYaGkC7mBPEinA-1)
