### ISSUE TITLE
Invite new team member modal

### ISSUE THREAD

**Issue by Paxxack** [bluewave-labs/bluewave-dataroom#41]
Here is the window popup needed for that feature

![image](https://github.com/user-attachments/assets/424553cb-8a38-4049-bf77-2443abcc2829)

Tasks list

- [x] General layout
- [x] 1 Text input field
- [x] 1 Select input field 
- [x] "Cancel" button
- [x] "Send invite" button

- [x] Alert like confirmation popup
- [x] Disappear after several seconds functionality
- [ ] "X" button

**Comment by NohaFahmi** [comment]
Hi @Paxxack, can I work on this?
