### ISSUE TITLE
Documents page - Main section - 1/2

### ISSUE THREAD

**Issue by neerajsunil** [bluewave-labs/bluewave-dataroom#5]
The documents page of the DataRoom application has the following features:

- Empty Documents view: This view shows a main welcome page when first using the DataRoom application or when no documents have been uploaded to the application.

Here's the view with no documents in the application:
![Documents page](https://github.com/user-attachments/assets/e569cbcd-652e-41df-a779-35cb2cf418b6)

- Documents view: This view shows the Documents page once Documents have been uploaded to the application. This view will also have pagination when the number of documents exceeds the view.

Documents view without pagination:
<img width="892" alt="Screenshot 2024-08-22 at 11 59 36 PM" src="https://github.com/user-attachments/assets/78fa3e52-4039-40d2-a77c-662f2352dabf">

Documents view with pagination:
<img width="1061" alt="Screenshot 2024-08-23 at 12 00 16 AM" src="https://github.com/user-attachments/assets/90206e32-99c5-4cc5-b913-ea257bd18840">

- Each document in the Documents page will have an action button with option to: Create Link, Duplicate, Update, View, and Delete

- [x] Implement empty documents view
    - [x] General visual
    - [x] Drag and drop functionality
- [ ] Implement documents view
    - [x] Document count (Under "Manage your documents " title)
    - [x] Upload new document button(top right corner on the page)
       - [x] Upload new document general layout
       - [x] "Click to load" link functionality
       - [x] Drag and drop functionality
       - [x] "Update" button
    - [x] List of document
       - [x] List header
       - [x] Display information about each uploaded document
       - [x] Action menu
          - [ ] Implement "Add new link"
          - [ ] Implement "Duplicate document" 
          - [ ] Implement "Update document"
             - [ ] Reuse the same Upload document component above with according text
          - [ ] implement "View analytics"
          - [ ] implement "Delete" 
             - [ ] General layout
             - [ ] "Cancel" button
             - [ ] "Delete file" button
- [ ] Implement "Create a new link" popup
   - [ ] "Create a new link" functionality

**Comment by gorkem-bwl** [comment]
Once it is completed (or before the completion), could you please send screenshots so I can have a look and comment for UI/UX side of the things?
