### ISSUE TITLE
General Fixes

### ISSUE THREAD

**Issue by Paxxack** [bluewave-labs/bluewave-dataroom#66]
- [x] Button ripple effect need to be removed ( Global Theme).
- [x] The app background color scheme need to be adjusted as shown on the Figma. (White backgrounds) 
- [x] We need to add a box shadow to the popup menus across the app.

**Comment by mahid797** [comment]
@Paxxack 
Regarding adding the box shadows to popup menus, need some clarification. It seems most of the menus already have shadows applied. Are there specific menus that lack shadows, or is the goal to unify the shadow style across all menus? Right now, the shadows for different menus differ in the Figma design.

Currently, the menus we have include:
- **Sidebar Dropdown Menu**
- **Dropdown Selects**
- **Action Menu** (in the Document Page table)

**Comment by gorkem-bwl** [comment]
As far as I remember, it was the action menu of the main dashboard table if I am not mistaken. If we can unify the shadow style across all menus, that would be great. There may be some inconsistencies in the Figma design, and you can ignore them - coming up with your own menu shadow template to provide a consistent look and feel.

**Comment by mahid797** [comment]
Shadow Consistency will be fixed in the #65 along with other GlobalTheme related changes
