### ISSUE TITLE
Contacts page

### ISSUE THREAD

**Issue by neerajsunil** [bluewave-labs/bluewave-dataroom#7]
The contacts page of the DataRoom application list all users who signed up to view or visit a link. This page is used to monitor the users currently using the application. It shows the total amount of times they have viewed a document, the latest document they viewed, and the last time they interacted with a document.

Here's the view for the contacts page:
![image](https://github.com/user-attachments/assets/d7c7fac1-8f51-4e18-80a0-4f3779f23fe7)

- [x] Implement contacts tabs
- [ ] Implement fetching latest user activity for each user

**Comment by gorkem-bwl** [comment]
I noticed I haven't dug into the design when the user views a document and needs to enter a name, surname and password which will eventually feed this dashboard. 

I will do that eventually once we start implementing the Contacts feature.

**Comment by gorkem-bwl** [comment]
Notes: 

- A user can view a document multiple times, and each of those visits is a view. 
- If the user enters name, surname and email, he shouldn't have to reenter this information again, and should be granted to view the file.
- PDFjs (https://github.com/mozilla/pdf.js) can be used to view the file when accessed.

**Comment by gorkem-bwl** [comment]
Added "When there are more than 10 contacts, show pagination" to the initial issue description.
