### ISSUE TITLE
Pagination component fix

### ISSUE THREAD

**Issue by Paxxack** [bluewave-labs/bluewave-dataroom#75]
- [x] We need to align center the text on the buttons.

**Comment by gorkem-bwl** [comment]
Previously what we have seen with Fred was that the icons were not aligned with the text. However in your design it looks ok. Let's keep this open as I'm sure we can find that issue again. 

Just FYI, do the icons have 1.5px stroke or is it 2px stroke there in the design?

**Comment by gorkem-bwl** [comment]
Sorry I meant 1px stroke. Here is how it looks in Figma. 

<img width="553" alt="SCR-20241030-rdow" src="https://github.com/user-attachments/assets/23942c39-05a7-4939-bcf8-00fcfcf2995d">

Note that you need to select the content of the image itself, not the bounding frame. Here I am selecting the bounding frame and it doesn't show the stroke:

<img width="552" alt="image" src="https://github.com/user-attachments/assets/3388821d-b581-42f3-8642-83fcf40fe2e8">
